In [2]:
import requests
from dotenv import load_dotenv
import os
from urllib.parse import quote

load_dotenv()

api_key = os.getenv("GEOAPIFY_API_KEY")

text = "1600 "  
encoded_text = quote(text)  

url = (
    "https://api.geoapify.com/v1/geocode/search?"
    f"text={encoded_text}"
    "&filter=circle:-77.03460987083406,38.89380923044945,120000"
    "&format=json"
    f"&apiKey={api_key}"
)

response = requests.get(url)

# Handle the response
if response.status_code == 200:
    data = response.json()

    if data['results'] == []:
        print("None")
    else:
        print(data['results'])
        for results in data['results']:
            print(results["formatted"])
            print(results["lon"])
            

    print(f"Error: {response.status_code}")
    print(response.text)

/Users/terrelldavis/Desktop/Personal Projects/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [3]:
import pandas as pd 


crime_data = pd.read_csv("/Users/terrelldavis/Desktop/Personal Projects/SafeRadiusDC/dc-crimes-search-results.csv")

crime_data["START_DATE"] = pd.to_datetime(crime_data["START_DATE"], format="%m/%d/%Y, %I:%M:%S %p")
crime_data["MONTH"] = crime_data['START_DATE'].dt.month_name()
crime_data["DAY_NUMBER"] = crime_data['START_DATE'].dt.days_in_month
numerical_desc = crime_data.groupby("OFFENSE")[['DAY_NUMBER']].describe()

categorical_desc = crime_data.groupby("OFFENSE")[['METHOD', 'SHIFT', 'BLOCK','MONTH']].describe(include='all')

df_describe = pd.concat([numerical_desc, categorical_desc], axis=1)
#df_describe.columns = ['_'.join(col).strip() for col in df_describe.columns.values]

#df_describe.to_csv("/Users/terrelldavis/Desktop/Personal Projects/SafeRadiusDC/infotest.csv", index=False)
df_describe

                           DAY_NUMBER                                          \
                                count       mean       std   min    25%   50%
OFFENSE
arson                             4.0  30.000000  0.816497  29.0  29.75  30.0
assault w/dangerous weapon      800.0  30.458750  0.652941  29.0  30.00  31.0
burglary                        722.0  30.508310  0.636881  29.0  30.00  31.0
homicide                        142.0  30.443662  0.668699  29.0  30.00  31.0
motor vehicle theft            3697.0  30.481201  0.659378  29.0  30.00  31.0
robbery                        1593.0  30.445700  0.678804  29.0  30.00  31.0
sex abuse                       121.0  30.446281  0.694627  28.0  30.00  31.0
theft f/auto                   4845.0  30.460475  0.669262  29.0  30.00  31.0
theft/other                    9345.0  30.478866  0.670763  29.0  30.00  31.0

                                        METHOD         ...     SHIFT        \
                              75%   max  count unique  ...       top  freq
OFFENSE                                                ...
arson                       30.25  31.0      4      1  ...   evening     3
assault w/dangerous weapon  31.00  31.0    801      3  ...  midnight   362
burglary                    31.00  31.0    722      3  ...       day   313
homicide                    31.00  31.0    142      3  ...  midnight   142
motor vehicle theft         31.00  31.0   3699      3  ...       day  1518
robbery                     31.00  31.0   1593      3  ...  midnight   708
sex abuse                   31.00  31.0    121      3  ...   evening    53
theft f/auto                31.00  31.0   4846      3  ...       day  2342
theft/other                 31.00  31.0   9345      3  ...   evening  4291

                           BLOCK         \
                           count unique
OFFENSE
arson                          4      4
assault w/dangerous weapon   801    626
burglary                     722    550
homicide                     142    131
motor vehicle theft         3699   2393
robbery                     1593   1260
sex abuse                    121    115
theft f/auto                4846   2923
theft/other                 9345   2885

                                                                            \
                                                                  top freq
OFFENSE
arson                                900 - 999 block of 5th street se    1
assault w/dangerous weapon   4000 - 4121 block of minnesota avenue ne   10
burglary                             1500 - 1599 block of u street nw    7
homicide                           4916 - 5066 block of jay street ne    3
motor vehicle theft         500 - 799 block of rhode island avenue ne   32
robbery                              1100 - 1199 block of u street nw    7
sex abuse                            900 - 999 block of 9th street nw    2
theft f/auto                500 - 799 block of rhode island avenue ne   31
theft/other                       3100 - 3299 block of 14th street nw  277

                           MONTH
                           count unique      top  freq
OFFENSE
arson                          4      4    March     1
assault w/dangerous weapon   800      9     June   116
burglary                     722     11   August   118
homicide                     142     11     July    19
motor vehicle theft         3697     12      May   462
robbery                     1593     10  January   216
sex abuse                    121     11    April    19
theft f/auto                4845     12      May   645
theft/other                 9345     12     July  1240

[9 rows x 24 columns]

In [6]:
crime_data = pd.read_csv("dc-crimes-search-results.csv")